# Created with package:mono_repo v3.4.2
language: dart

# Custom configuration
branches:
  only:
    - master

jobs:
  include:
    - stage: work
      name: mono_repo self validate
      os: linux
      script: "pub global activate mono_repo 3.4.2 && pub global run mono_repo generate --validate"
    - stage: work
      name: "PKGS: _shared_assets, firebase; `dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-infos .`"
      dart: dev
      os: linux
      env: PKGS="_shared_assets firebase"
      script: tool/ci.sh dartfmt dartanalyzer
    - stage: work
      name: "PKG: firebase; `pub run build_runner build example --fail-on-severe --delete-conflicting-outputs`"
      dart: dev
      os: linux
      env: PKGS="firebase"
      script: tool/ci.sh command_0
    - stage: work
      name: "PKG: firebase; `pushd ../_shared_assets && pub get && dart create_config.dart && popd && pub run test`"
      dart: dev
      os: linux
      env: PKGS="firebase"
      script: tool/ci.sh command_1

stages:
  - work

cache:
  directories:
    - $HOME/.pub-cache
    - _shared_assets/.dart_tool/build
    - firebase/.dart_tool/build
